# Generated by Django 5.2.7 on 2025-11-17 21:14

import shelters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=shelters.models.shelter_photo_upload_path),
        ),
    ]
