# Generated by Django 5.2.7 on 2025-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pet_type', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
    ]
