# Generated by Django 5.2.7 on 2025-11-17 21:02

import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_owner_alter_pet_shelter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pets.models.pet_photo_upload_path),
        ),
    ]
