# Generated by Django 5.2.7 on 2025-11-17 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_petphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='petphoto',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together={('pet', 'user')},
        ),
    ]
