# Generated by Django 5.2.7 on 2025-11-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_petphoto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age_unit',
            field=models.CharField(blank=True, choices=[('months', 'Meses'), ('years', 'Años')], default='years', help_text='Unidad de edad (meses o años)', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, help_text='Edad numérica', null=True),
        ),
    ]
