# Generated by Django 5.2.7 on 2025-11-17 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Un usuario con ese nombre ya existe.'}, help_text='Requerido. 3-30 caracteres. Letras, números, espacios, guiones (-) y guiones bajos (_).', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de usuario debe tener entre 3 y 30 caracteres y solo puede contener letras, números, espacios, guiones (-) y guiones bajos (_).', regex='^[a-zA-Z0-9\\s_-]{3,30}$')]),
        ),
    ]
